# Generated by Django 5.0.2 on 2024-05-31 05:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_time", models.DateTimeField(auto_now=True)),
                ("data", models.DateField(verbose_name="Дата")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Одобрено", "Одобрено"),
                            ("Отклонено", "Отклонено"),
                            ("НОВАЯ", "НОВАЯ"),
                        ],
                        default="НОВАЯ",
                        max_length=20,
                        null=True,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "type_order",
                    models.CharField(
                        choices=[
                            ("Образец", "Образец"),
                            ("Экспорт", "Экспорт"),
                            ("Внутренный рынок", "Внутренный рынок"),
                            ("Услуга", "Услуга"),
                        ],
                        max_length=100,
                        verbose_name="Тип заказа",
                    ),
                ),
                (
                    "date_of_production",
                    models.DateField(verbose_name="Дата производства"),
                ),
            ],
            options={
                "verbose_name": "Заказ коробки",
                "verbose_name_plural": "Заказы коробок",
            },
        ),
        migrations.CreateModel(
            name="BoxOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Детали заказа коробки",
                "verbose_name_plural": "Детали заказов коробок",
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "queue",
                    models.PositiveIntegerField(
                        blank=True, default=None, null=True, verbose_name="Очеред"
                    ),
                ),
            ],
            options={
                "verbose_name": "Процесс",
                "verbose_name_plural": "Процессы",
            },
        ),
        migrations.CreateModel(
            name="ProcessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Временная метка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Процесс производства",
                "verbose_name_plural": "Процессы производства",
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="Код"
                    ),
                ),
                (
                    "shipping_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата доставки"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Количество"
                    ),
                ),
                (
                    "packed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Количество упаковано",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("В работе", "В работе"),
                            ("ЗАКОНЧЕНО", "ЗАКОНЧЕНО"),
                            ("НОВАЯ", "НОВАЯ"),
                            ("Упаковано", "Упаковано"),
                        ],
                        default="НОВАЯ",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Производственный заказ",
                "verbose_name_plural": "Производственные заказы",
            },
        ),
        migrations.CreateModel(
            name="TypeWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Тип работы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип работы",
                "verbose_name_plural": "Типы работы",
            },
        ),
        migrations.CreateModel(
            name="BoxModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        default="box_photos/box_foto.png",
                        upload_to="box_photos",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "heic"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "closure_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Склейка"),
                            (2, "Клапаны"),
                            (3, "Автозамок"),
                            (4, "Скобы"),
                            (5, "Ленты или бандероли"),
                            (6, "Крючки или зажимы"),
                            (7, "Вкладыш"),
                            (8, "Магниты"),
                        ],
                        null=True,
                        verbose_name="Тип замыкания",
                    ),
                ),
                (
                    "additional_properties",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Влагостойкость"),
                            (2, "Устойчивость к воздействию"),
                            (3, "Экологичность"),
                            (4, "Теплоизоляция"),
                            (5, "Антистатические свойства"),
                        ],
                        null=True,
                        verbose_name="Дополнительные свойства",
                    ),
                ),
                (
                    "max_load",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Максимальная нагрузка",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Цвет"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "grams_per_box",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Грамм на одну коробку",
                    ),
                ),
                (
                    "box_size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="box_models_with_size",
                        to="info.boxsize",
                        verbose_name="Размер коробки",
                    ),
                ),
                (
                    "box_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="box_models_with_type",
                        to="info.boxtype",
                        verbose_name="Тип коробки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель коробки",
                "verbose_name_plural": "Модели коробок",
                "ordering": ["-created_time"],
            },
        ),
    ]
