# Generated by Django 5.0.2 on 2024-05-31 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("info", "0002_initial"),
        ("production", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boxmodel",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="boxmodel",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info.material",
                verbose_name="Материал",
            ),
        ),
        migrations.AddField(
            model_name="boxmodel",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="boxorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="boxorder",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="info.firm",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="boxorder",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AddField(
            model_name="boxorder",
            name="specification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="info.specification",
                verbose_name="Спецификация",
            ),
        ),
        migrations.AddField(
            model_name="boxorder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="boxorderdetail",
            name="box_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="production.boxmodel",
                verbose_name="Модель коробки",
            ),
        ),
        migrations.AddField(
            model_name="boxorderdetail",
            name="box_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="production.boxorder",
                verbose_name="Заказ коробки",
            ),
        ),
        migrations.AddField(
            model_name="processlog",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="production.process",
                verbose_name="Процесс",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="box_order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_orders",
                to="production.boxorderdetail",
                verbose_name="Детали заказа коробки",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="processlog",
            name="production_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_logs",
                to="production.productionorder",
                verbose_name="Заказ на производство",
            ),
        ),
        migrations.AddField(
            model_name="typework",
            name="process",
            field=models.ManyToManyField(
                to="production.process", verbose_name="Процесс"
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="type_of_work",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="production.typework",
                verbose_name="Тип Работы",
            ),
        ),
    ]
