# Generated by Django 5.0.2 on 2024-03-26 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("production", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boxorder",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="boxorder",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="boxorder",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="boxorderdetail",
            name="box_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="production.boxmodel"
            ),
        ),
        migrations.AddField(
            model_name="boxorderdetail",
            name="box_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="production.boxorder"
            ),
        ),
        migrations.AddField(
            model_name="boxmodel",
            name="type_of_work",
            field=models.ManyToManyField(
                blank=True, related_name="processes", to="production.process"
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="box_order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_orders",
                to="production.boxorderdetail",
            ),
        ),
        migrations.AddField(
            model_name="boxmodel",
            name="photos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_model",
                to="production.uploadimage",
            ),
        ),
    ]
