# Generated by Django 5.0.2 on 2024-07-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_initial"),
        ("production", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxmodel",
            name="additional_materials",
            field=models.ManyToManyField(
                related_name="additional_box_models",
                to="info.material",
                verbose_name="Дополнительные материалы",
            ),
        ),
        migrations.AlterField(
            model_name="boxmodel",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_models",
                to="info.material",
                verbose_name="Материал",
            ),
        ),
    ]
