# Generated by Django 5.0.2 on 2024-04-22 12:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_alter_boxsize_options_alter_boxtype_options_and_more"),
        ("production", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boxmodel",
            options={
                "ordering": ["-created_time"],
                "verbose_name": "Модель коробки",
                "verbose_name_plural": "Модели коробок",
            },
        ),
        migrations.AlterModelOptions(
            name="boxorder",
            options={
                "verbose_name": "Заказ коробки",
                "verbose_name_plural": "Заказы коробок",
            },
        ),
        migrations.AlterModelOptions(
            name="boxorderdetail",
            options={
                "verbose_name": "Детали заказа коробки",
                "verbose_name_plural": "Детали заказов коробок",
            },
        ),
        migrations.AlterModelOptions(
            name="process",
            options={"verbose_name": "Процесс", "verbose_name_plural": "Процессы"},
        ),
        migrations.AlterModelOptions(
            name="productionorder",
            options={
                "verbose_name": "Производственный заказ",
                "verbose_name_plural": "Производственные заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="uploadimage",
            options={
                "verbose_name": "Загруженное изображение",
                "verbose_name_plural": "Загруженные изображения",
            },
        ),
        migrations.AlterField(
            model_name="boxmodel",
            name="box_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="box_models_with_size",
                to="info.boxsize",
                verbose_name="Размер коробки",
            ),
        ),
        migrations.AlterField(
            model_name="boxmodel",
            name="box_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="box_models_with_type",
                to="info.boxtype",
                verbose_name="Тип коробки",
            ),
        ),
        migrations.AlterField(
            model_name="boxmodel",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info.material",
                verbose_name="Материал",
            ),
        ),
        migrations.AlterField(
            model_name="boxmodel",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="boxmodel",
            name="photos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="box_model",
                to="production.uploadimage",
                verbose_name="Фотографии",
            ),
        ),
        migrations.AlterField(
            model_name="boxmodel",
            name="type_of_work",
            field=models.ManyToManyField(
                blank=True,
                related_name="processes",
                to="production.process",
                verbose_name="Тип работы",
            ),
        ),
        migrations.AlterField(
            model_name="boxorder",
            name="customer",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Клиент"
            ),
        ),
        migrations.AlterField(
            model_name="boxorder",
            name="data",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="boxorder",
            name="date_of_production",
            field=models.DateField(verbose_name="Дата производства"),
        ),
        migrations.AlterField(
            model_name="boxorder",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
        migrations.AlterField(
            model_name="boxorder",
            name="specification",
            field=models.CharField(max_length=100, verbose_name="Спецификация"),
        ),
        migrations.AlterField(
            model_name="boxorder",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Одобрено", "Одобрено"),
                    ("Отклонено", "Отклонено"),
                    ("НОВАЯ", "НОВАЯ"),
                ],
                default="НОВАЯ",
                max_length=20,
                null=True,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="boxorder",
            name="type_order",
            field=models.CharField(max_length=100, verbose_name="Тип заказа"),
        ),
        migrations.AlterField(
            model_name="boxorderdetail",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="boxorderdetail",
            name="box_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="production.boxmodel",
                verbose_name="Модель коробки",
            ),
        ),
        migrations.AlterField(
            model_name="boxorderdetail",
            name="box_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="production.boxorder",
                verbose_name="Заказ коробки",
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="box_order_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_orders",
                to="production.boxorderdetail",
                verbose_name="Детали заказа коробки",
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="shipping_date",
            field=models.DateField(verbose_name="Дата доставки"),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("not_started", "Not Started"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="uploadimage",
            name="photo",
            field=models.ImageField(
                default="no-image.png",
                upload_to="box_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic"]
                    )
                ],
                verbose_name="Изображение",
            ),
        ),
    ]
