# Generated by Django 5.0.2 on 2024-04-01 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_alter_boxmodel_options_boxmodel_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxmodel",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="boxorder",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
