# Generated by Django 5.0.2 on 2024-04-23 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_alter_boxmodel_options_alter_boxorder_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boxmodel",
            name="photos",
        ),
        migrations.AddField(
            model_name="boxmodel",
            name="photo",
            field=models.ImageField(
                default="no-image.png",
                upload_to="box_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic"]
                    )
                ],
                verbose_name="Изображение",
            ),
        ),
        migrations.DeleteModel(
            name="UploadImage",
        ),
    ]
