# Generated by Django 5.0.2 on 2024-04-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_alter_boxmodel_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxorderdetail",
            name="box_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="production.boxorder",
            ),
        ),
    ]
