# Generated by Django 5.0.2 on 2024-07-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_boxmodel_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxmodel",
            name="layers",
            field=models.IntegerField(
                choices=[(3, "3 слоя"), (5, "5 слоев")],
                default=3,
                verbose_name="Слоистость",
            ),
        ),
    ]
