# Generated by Django 5.0.2 on 2024-04-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_remove_boxmodel_photos_boxmodel_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boxmodel",
            name="type_of_work",
        ),
        migrations.AddField(
            model_name="productionorder",
            name="type_of_work",
            field=models.ManyToManyField(
                blank=True,
                related_name="processes",
                to="production.process",
                verbose_name="Тип работы",
            ),
        ),
    ]
