# Generated by Django 5.0.2 on 2024-04-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_material_unit_of_measurement"),
        ("production", "0005_remove_boxmodel_type_of_work_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxorder",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="info.firm",
                verbose_name="Клиент",
            ),
        ),
    ]
