# Generated by Django 5.0.2 on 2024-07-17 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_alter_boxsize_name_alter_material_code_and_more"),
        ("production", "0006_alter_boxmodel_layers"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxorder",
            name="buyer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buyers",
                to="info.firm",
                verbose_name="Покупатель",
            ),
        ),
    ]
