# Generated by Django 5.0.2 on 2024-04-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_alter_boxorder_customer_alter_boxorder_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxorder",
            name="type_order",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
