# Generated by Django 5.0.2 on 2024-04-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_material_unit_of_measurement"),
        ("production", "0006_alter_boxorder_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxorder",
            name="specification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="info.specification",
                verbose_name="Спецификация",
            ),
        ),
    ]
