# Generated by Django 5.0.2 on 2024-04-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0007_alter_boxorder_type_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxorder",
            name="specification",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
