# Generated by Django 5.0.2 on 2024-07-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0007_boxorder_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxmodel",
            name="grams_per_box",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Грамм на одну коробку",
            ),
        ),
    ]
