# Generated by Django 5.0.2 on 2024-07-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0005_remove_outgoing_production_order_and_more"),
        ("production", "0008_alter_boxmodel_grams_per_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="outgoing_materials",
            field=models.ManyToManyField(
                blank=True,
                related_name="production_orders",
                to="depo.outgoingmaterial",
                verbose_name="Исходящие материалы",
            ),
        ),
    ]
