# Generated by Django 5.0.2 on 2024-07-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0005_remove_outgoing_production_order_and_more"),
        ("production", "0009_productionorder_outgoing_materials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionorder",
            name="outgoing_materials",
        ),
        migrations.AddField(
            model_name="productionorder",
            name="outgoing_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_orders",
                to="depo.outgoingmaterial",
                verbose_name="Исходящая поставка",
            ),
        ),
    ]
