# Generated by Django 5.0.2 on 2024-04-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0009_alter_boxmodel_photo_alter_process_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="process",
            options={"verbose_name": "Процесс", "verbose_name_plural": "Процессы"},
        ),
    ]
