# Generated by Django 5.0.2 on 2024-07-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0010_remove_productionorder_outgoing_materials_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productionorder",
            name="outgoing_material",
        ),
    ]
