# Generated by Django 5.0.2 on 2024-07-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0009_remove_outgoing_production_order_and_more"),
        ("production", "0011_remove_productionorder_outgoing_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="outgoing_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_orders_related",
                to="depo.outgoingmaterial",
                verbose_name="Исходящая поставка",
            ),
        ),
    ]
