# Generated by Django 5.0.2 on 2024-08-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0012_alter_material_norm"),
        ("production", "0012_productionorder_outgoing_material"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typework",
            options={"verbose_name": "Вид работы", "verbose_name_plural": "Виды работ"},
        ),
        migrations.AlterField(
            model_name="boxmodel",
            name="additional_materials",
            field=models.ManyToManyField(
                blank=True,
                related_name="additional_box_models",
                to="info.material",
                verbose_name="Дополнительные материалы",
            ),
        ),
        migrations.AlterField(
            model_name="typework",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Вид работы"
            ),
        ),
    ]
