# Generated by Django 5.0.2 on 2024-08-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0015_alter_boxmodel_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boxmodel",
            name="format",
        ),
    ]
