# Generated by Django 5.0.2 on 2024-05-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0015_productionorder_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="Код"
            ),
        ),
    ]
