# Generated by Django 5.0.2 on 2024-05-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0017_alter_productionorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("В работе", "В работе"),
                    ("ЗАКОНЧЕНО", "ЗАКОНЧЕНО"),
                    ("НОВАЯ", "НОВАЯ"),
                ],
                default="НОВАЯ",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
