# Generated by Django 5.0.2 on 2024-05-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0018_alter_productionorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="queue",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="Очеред"
            ),
        ),
    ]
