# Generated by Django 5.0.2 on 2024-05-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0020_processlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processlog",
            options={
                "verbose_name": "Процесс производства",
                "verbose_name_plural": "Процессы производства",
            },
        ),
        migrations.AddField(
            model_name="productionorder",
            name="packed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Количество упаковано",
            ),
        ),
        migrations.AlterField(
            model_name="productionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("В работе", "В работе"),
                    ("ЗАКОНЧЕНО", "ЗАКОНЧЕНО"),
                    ("НОВАЯ", "НОВАЯ"),
                    ("Упаковано", "Упаковано"),
                ],
                default="НОВАЯ",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
