# Generated by Django 5.0.2 on 2024-05-30 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0023_alter_boxmodel_grams_per_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxmodel",
            name="photo",
            field=models.ImageField(
                default="box_photos/box_foto.png",
                upload_to="box_photos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic"]
                    )
                ],
                verbose_name="Изображение",
            ),
        ),
    ]
