# Generated by Django 5.0.2 on 2024-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0024_alter_boxmodel_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxmodel",
            name="grams_per_box",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                verbose_name="Грамм на одну коробку",
            ),
        ),
    ]
