# Generated by Django 5.0.2 on 2024-04-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0002_initial"),
        ("info", "0003_alter_boxsize_options_alter_boxtype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incoming",
            options={"verbose_name": "Приход", "verbose_name_plural": "Приходы"},
        ),
        migrations.AlterModelOptions(
            name="incomingmaterial",
            options={
                "verbose_name": "Материал прихода",
                "verbose_name_plural": "Материалы прихода",
            },
        ),
        migrations.AlterModelOptions(
            name="outgoing",
            options={"verbose_name": "Расход", "verbose_name_plural": "Расходы"},
        ),
        migrations.AlterModelOptions(
            name="outgoingmaterial",
            options={
                "verbose_name": "Материал расхода",
                "verbose_name_plural": "Материалы расхода",
            },
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={
                "verbose_name": "Остаток на складе",
                "verbose_name_plural": "Остатки на складе",
            },
        ),
        migrations.AlterField(
            model_name="incoming",
            name="contract_number",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Номер контракта"
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="data",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="from_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_from_warehouse",
                to="info.warehouse",
                verbose_name="От склада",
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="incoming_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Перемещение", "Перемещение"),
                    ("По накладной", "По накладной"),
                ],
                max_length=150,
                null=True,
                verbose_name="Тип поступления",
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="invoice",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Накладная"
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="note",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Примечание"
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="outgoing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="depo.outgoing",
                verbose_name="Исходящий",
            ),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_warehouse",
                to="info.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.AlterField(
            model_name="incomingmaterial",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="incomingmaterial",
            name="comment",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="incomingmaterial",
            name="incoming",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="depo.incoming",
                verbose_name="Поступление",
            ),
        ),
        migrations.AlterField(
            model_name="incomingmaterial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info.material",
                verbose_name="Материал",
            ),
        ),
        migrations.AlterField(
            model_name="incomingmaterial",
            name="material_party",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Партия материала"
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="code",
            field=models.CharField(
                editable=False, max_length=10, unique=True, verbose_name="Код"
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="data",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="note",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Примечание"
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="outgoing_type",
            field=models.CharField(
                choices=[
                    ("расход", "Расход"),
                    ("продажа", "Продажа"),
                    ("перемешения", "Перемещение"),
                ],
                default="перемешения",
                max_length=20,
                verbose_name="Тип исхода",
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Принят", "Принят"),
                    ("Отклонен", "Отклонен"),
                    ("В ожидании", "В ожидании"),
                ],
                default="В ожидании",
                max_length=20,
                null=True,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="to_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_to_warehouse",
                to="info.warehouse",
                verbose_name="К складу",
            ),
        ),
        migrations.AlterField(
            model_name="outgoing",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_warehouse",
                to="info.warehouse",
                verbose_name="Склад",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingmaterial",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="outgoingmaterial",
            name="comment",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="outgoingmaterial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info.material",
                verbose_name="Материал",
            ),
        ),
        migrations.AlterField(
            model_name="outgoingmaterial",
            name="material_party",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Партия материала"
            ),
        ),
        migrations.AlterField(
            model_name="outgoingmaterial",
            name="outgoing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_materials",
                to="depo.outgoing",
                verbose_name="Исходящая поставка",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info.material",
                verbose_name="Материал",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info.warehouse",
                verbose_name="Склад",
            ),
        ),
    ]
