# Generated by Django 5.0.2 on 2024-07-19 07:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0003_outgoingmaterial_production_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Количество",
            ),
        ),
    ]
