# Generated by Django 5.0.2 on 2024-04-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0003_alter_incoming_options_and_more"),
        ("info", "0006_alter_material_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="material",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="info.material",
                verbose_name="Материал",
            ),
        ),
    ]
