# Generated by Django 5.0.2 on 2024-07-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0004_alter_stock_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outgoing",
            name="production_order",
        ),
        migrations.RemoveField(
            model_name="outgoingmaterial",
            name="production_order",
        ),
    ]
