# Generated by Django 5.0.2 on 2024-04-30 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0004_alter_stock_material"),
        ("info", "0008_materialtype_created_by_materialtype_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incoming",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_warehouse",
                to="info.warehouse",
                verbose_name="Склад",
            ),
        ),
    ]
