# Generated by Django 5.0.2 on 2024-07-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0006_outgoingmaterial_production_order"),
        ("production", "0010_remove_productionorder_outgoing_materials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outgoingmaterial",
            name="production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_materials",
                to="production.productionorder",
                verbose_name="Заказ на производство",
            ),
        ),
    ]
