# Generated by Django 5.0.2 on 2024-05-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0006_stock_created_by_stock_created_time_stock_updated_by_and_more"),
        ("production", "0015_productionorder_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outgoing",
            name="production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoings",
                to="production.productionorder",
            ),
        ),
    ]
