# Generated by Django 5.0.2 on 2024-07-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0008_outgoing_production_order"),
        ("production", "0011_remove_productionorder_outgoing_material"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outgoing",
            name="production_order",
        ),
        migrations.AlterField(
            model_name="outgoingmaterial",
            name="production_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_materials_related",
                to="production.productionorder",
                verbose_name="Заказ на производство",
            ),
        ),
    ]
