# Generated by Django 5.0.2 on 2024-08-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depo", "0009_remove_outgoing_production_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outgoing",
            name="outgoing_type",
            field=models.CharField(
                choices=[
                    ("расход", "Расход"),
                    ("продажа", "Продажа"),
                    ("перемешения", "Перемещение"),
                ],
                default="перемешения",
                max_length=20,
                verbose_name="Тип расхода",
            ),
        ),
    ]
