# Generated by Django 5.0.2 on 2024-04-01 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
