# Generated by Django 5.0.2 on 2024-04-01 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firm",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="material",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="specification",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="can_export",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="can_import",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="use_negative",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
