# Generated by Django 5.0.2 on 2024-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxsize",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="code",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Код"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_thickness",
            field=models.FloatField(null=True, verbose_name="Плотность(Г/м2)"),
        ),
    ]
