# Generated by Django 5.0.2 on 2024-04-22 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boxsize",
            options={
                "verbose_name": "Размер коробки",
                "verbose_name_plural": "Размеры коробок",
            },
        ),
        migrations.AlterModelOptions(
            name="boxtype",
            options={
                "verbose_name": "Тип коробки",
                "verbose_name_plural": "Типы коробок",
            },
        ),
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Бренд", "verbose_name_plural": "Бренды"},
        ),
        migrations.AlterModelOptions(
            name="firm",
            options={"verbose_name": "Фирма", "verbose_name_plural": "Фирмы"},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"verbose_name": "Материал", "verbose_name_plural": "Материалы"},
        ),
        migrations.AlterModelOptions(
            name="materialgroup",
            options={
                "verbose_name": "Группа материалов",
                "verbose_name_plural": "Группы материалов",
            },
        ),
        migrations.AlterModelOptions(
            name="materialspecialgroup",
            options={
                "verbose_name": "Специальная группа материалов",
                "verbose_name_plural": "Специальные группы материалов",
            },
        ),
        migrations.AlterModelOptions(
            name="materialtype",
            options={
                "verbose_name": "Тип материала",
                "verbose_name_plural": "Типы материалов",
            },
        ),
        migrations.AlterModelOptions(
            name="specification",
            options={
                "verbose_name": "Спецификация",
                "verbose_name_plural": "Спецификации",
            },
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"verbose_name": "Склад", "verbose_name_plural": "Склады"},
        ),
        migrations.AddField(
            model_name="material",
            name="unit_of_measurement",
            field=models.CharField(
                choices=[
                    ("sht", "шт"),
                    ("sm", "см"),
                    ("mm", "мм"),
                    ("kg", "кг"),
                    ("litr", "л"),
                ],
                default=None,
                max_length=10,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="boxsize",
            name="height",
            field=models.PositiveIntegerField(verbose_name="Высота"),
        ),
        migrations.AlterField(
            model_name="boxsize",
            name="length",
            field=models.PositiveIntegerField(verbose_name="Длина"),
        ),
        migrations.AlterField(
            model_name="boxsize",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="boxsize",
            name="width",
            field=models.PositiveIntegerField(verbose_name="Ширина"),
        ),
        migrations.AlterField(
            model_name="boxtype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="firm",
            name="actual_address",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Фактический адрес"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True, verbose_name="Код"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Активна"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="legal_address",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Юридический адрес"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="license_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Номер лицензии"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="mfo",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="МФО"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="firm",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="type_firm",
            field=models.CharField(
                choices=[
                    ("supplier", "Поставщик"),
                    ("customer", "Заказчик"),
                    ("both", "Поставщик и Заказчик"),
                ],
                max_length=20,
                verbose_name="Тип фирмы",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info.brand",
                verbose_name="Бренд",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="code",
            field=models.CharField(max_length=100, unique=True, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info.materialgroup",
                verbose_name="Группа материала",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_thickness",
            field=models.FloatField(verbose_name="Толщина материала"),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_type",
            field=models.ForeignKey(
                max_length=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="info.materialtype",
                verbose_name="Тип материала",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="special_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info.materialspecialgroup",
                verbose_name="Специальная группа",
            ),
        ),
        migrations.AlterField(
            model_name="materialgroup",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="materialspecialgroup",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="materialtype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="specification",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="info.firm",
                verbose_name="Фирма",
            ),
        ),
        migrations.AlterField(
            model_name="specification",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="specification",
            name="year",
            field=models.CharField(max_length=4, verbose_name="Год"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="can_export",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Может экспортировать",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="can_import",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Может импортировать"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True, verbose_name="Код"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Активен"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="location",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Местоположение"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="managers",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Менеджеры"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="use_negative",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Использовать отрицательные значения",
            ),
        ),
    ]
