# Generated by Django 5.0.2 on 2024-04-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_alter_boxsize_options_alter_boxtype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="unit_of_measurement",
        ),
    ]
