# Generated by Django 5.0.2 on 2024-07-18 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_alter_boxsize_name_alter_material_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="norm",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Норма для 1 м2",
            ),
        ),
    ]
