# Generated by Django 5.0.2 on 2024-07-19 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0004_material_norm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="norm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Норма для 1 м2",
            ),
        ),
    ]
