# Generated by Django 5.0.2 on 2024-04-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_material_unit_of_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="info.brand",
                verbose_name="Бренд",
            ),
        ),
    ]
