# Generated by Django 5.0.2 on 2024-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0005_alter_material_norm"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="type_material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("material", "Материал"),
                    ("ready_material", "Готовый продукт\t"),
                ],
                default="material",
                max_length=20,
                null=True,
            ),
        ),
    ]
