# Generated by Django 5.0.2 on 2024-04-30 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0008_materialtype_created_by_materialtype_created_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="photo",
            field=models.ImageField(
                default="box_photos/no-image.png",
                upload_to="box_photos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "heic"]
                    )
                ],
                verbose_name="Изображение",
            ),
        ),
    ]
