# Generated by Django 5.0.2 on 2024-08-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0008_alter_material_material_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="material_type",
            field=models.ForeignKey(
                blank=True,
                default=5,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="info.materialtype",
                verbose_name="Тип материала",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="special_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="info.materialspecialgroup",
                verbose_name="Специальная группа",
            ),
        ),
    ]
