# Generated by Django 5.0.2 on 2024-08-02 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0009_alter_material_material_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="info.brand",
                verbose_name="Бренд",
            ),
        ),
    ]
