# Generated by Django 5.0.2 on 2024-05-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0009_material_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="material_thickness",
            field=models.FloatField(verbose_name="Плотность(Г/м2)"),
        ),
    ]
