# Generated by Django 5.0.2 on 2024-08-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0010_alter_material_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="material_thickness",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Плотность(Г/м2)"
            ),
        ),
    ]
