# Generated by Django 5.0.2 on 2024-08-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0012_alter_material_norm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="material_type",
            field=models.ForeignKey(
                blank=True,
                default=1,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="info.materialtype",
                verbose_name="Тип материала",
            ),
        ),
    ]
