# Generated by Django 5.0.2 on 2024-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0013_alter_material_material_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boxsize",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Название",
            ),
        ),
    ]
