# Generated by Django 5.0.2 on 2024-08-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0016_alter_material_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="info.firm",
                verbose_name="Заказчик",
            ),
        ),
    ]
