# Generated by Django 5.0.2 on 2024-08-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0017_material_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="material_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="info.materialgroup",
                verbose_name="Группа материала",
            ),
        ),
    ]
